import React, { useState } from 'react';
import { generateStudyContent } from '../services/geminiService';
import BookLoader from './BookLoader';
import MarkdownContent from './MarkdownContent';
import SaveToFolderModal from './SaveToFolderModal';
import { QuizFolder, QuizQuestion, StudyProfile, EditalConfig, ExplanationStyle } from '../types';

interface AIViewProps {
  onBack: () => void;
  folders: QuizFolder[];
  onNewContent: (content: any) => void;
  onSaveToNotebook: (folderId: string, notebookName: string, questions: QuizQuestion[], summary?: string) => void;
  studyProfile: StudyProfile;
  prefill?: { topic: string; autoStart: boolean } | null;
  onConsumedPrefill?: () => void;
  strategicMode?: boolean;
  editalConfig?: EditalConfig;
  explanationStyle?: ExplanationStyle;
}

const AIView: React.FC<AIViewProps> = ({ onBack, onNewContent, onSaveToNotebook, folders, studyProfile, prefill, onConsumedPrefill, strategicMode, editalConfig, explanationStyle: initialStyle }) => {
  const [topic, setTopic] = useState(prefill?.topic || '');
  const [selectedSubject, setSelectedSubject] = useState<string>('');
  const [selectedTopic, setSelectedTopic] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [saved, setSaved] = useState(false);
  const [showSaveModal, setShowSaveModal] = useState(false);
  const [numQuestions, setNumQuestions] = useState(5);
  const [explanationStyle, setExplanationStyle] = useState<ExplanationStyle>(initialStyle || 'TECNICA');
  const [generatingCards, setGeneratingCards] = useState(false);

  React.useEffect(() => {
    if (prefill?.autoStart && prefill.topic) {
      handleGenerate(prefill.topic);
      onConsumedPrefill?.();
    }
  }, [prefill]);

  const handleGenerate = async (targetTopic?: string) => {
    const finalTopic = targetTopic || (strategicMode ? (selectedTopic ? `${selectedSubject}: ${selectedTopic}` : '') : topic);
    if (!finalTopic.trim()) return;

    setLoading(true);
    if (!targetTopic) setResult(null); // Reset total se for busca nova
    setSaved(false);

    try {
      const content = await generateStudyContent(finalTopic, 'Dossiê Expandido', numQuestions, studyProfile, explanationStyle);
      // We filter out flashcards if they were auto-generated by the service, as per user's request
      // But looking at the service, it's baked into the schema.
      // We will keep them in the result object but not call onNewContent immediately if we want to separate logic.
      // However, onNewContent in App.tsx adds to flashcards state.
      // The user wants AI cards only when asked.

      const contentWithoutAutoCards = { ...content, flashcards: [] };
      setResult(content); // Keep them in state but maybe don't "activate" them yet
      if (!targetTopic) setTopic(finalTopic);
      onNewContent(contentWithoutAutoCards);
      window.scrollTo({ top: 0, behavior: 'smooth' });
    } catch (error: any) {
      console.error(error);
      const msg = error.message || 'Erro ao mergulhar. Tente novamente.';
      alert(msg);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateFlashcards = async () => {
    if (!result || !topic.trim()) return;
    setGeneratingCards(true);

    try {
      // Actually generate a fresh batch of study content for the current topic
      // and take only the new flashcards from it (geminiService has no more
      // targeted "flashcards only" export, so we reuse generateStudyContent).
      const freshContent = await generateStudyContent(topic, 'Dossiê Expandido', numQuestions, studyProfile, explanationStyle);
      setResult((prev: any) => (prev ? { ...prev, flashcards: freshContent.flashcards } : prev));
      onNewContent({ ...freshContent, quiz: [] }); // Only send flashcards
      alert('Flashcards gerados e adicionados à sua revisão!');
    } catch (error: any) {
      console.error(error);
      const msg = error.message || 'Erro ao gerar flashcards. Tente novamente.';
      alert(msg);
    } finally {
      setGeneratingCards(false);
    }
  };

  const handleConfirmSave = (folderId: string, notebookName: string) => {
    if (result) {
      onSaveToNotebook(folderId, notebookName, result.quiz, result.executiveSummary);
      setSaved(true);
      setShowSaveModal(false);
    }
  };

  const canGenerate = strategicMode ? Boolean(selectedSubject && selectedTopic) : topic.trim().length > 0;

  if (loading) {
    return (
      <div className="relative isolate w-full min-h-[calc(100dvh-8rem)] rounded-[32px] bg-[#473c33] text-white selection:bg-[#fecc73]/30 p-3 sm:p-6">
        <div className="relative h-full min-h-[calc(100dvh-11rem)] w-full overflow-hidden rounded-[28px] border border-white/10 shadow-2xl flex flex-col items-center justify-center gap-6 animate-in fade-in duration-500">
          <BookLoader className="scale-[2.4] sm:scale-[3]" />
          <div className="text-center px-6 mt-4">
            <p className="text-white font-black text-xl tracking-tight drop-shadow-md">Mergulhando mais fundo...</p>
            <p className="text-white/70 text-[10px] font-bold uppercase tracking-[0.22em] leading-relaxed mt-2">A IA está organizando seu dossiê de alta performance</p>
          </div>
          <div className="absolute inset-x-0 top-0 z-20 flex items-center justify-between gap-4 p-4 sm:p-5 bg-[#473c33]/55 backdrop-blur-md border-b border-white/10">
            <button onClick={onBack} className="shrink-0 p-2.5 rounded-xl text-white/70 hover:text-white hover:bg-white/10 transition-all" aria-label="Cancelar exploração" title="Voltar">
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path d="M15 19l-7-7 7-7" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </button>
            <div className="min-w-0 flex-1 text-center sm:text-left">
              <p className="text-[9px] font-black uppercase tracking-[0.3em] text-[#fed386]">EXPLORAÇÃO ILIMITADA</p>
              <h1 className="mt-1 text-sm sm:text-base font-black text-white truncate">Preparando seu dossiê</h1>
            </div>
            <div className="hidden sm:flex items-center gap-2 shrink-0 text-[9px] font-black uppercase tracking-widest text-white/60">
              <span className="w-2 h-2 rounded-full bg-[#fecc73] animate-pulse" />
              Processando
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className={`relative isolate w-full min-h-full min-w-0 rounded-[32px] selection:bg-[#fecc73]/30 font-sans ${result ? 'bg-[#473c33] text-white' : 'bg-[#f7f3ed] text-[#473c33]'}`}>
      <div className="w-full max-w-7xl mx-auto px-4 sm:px-6 xl:px-10 pt-6 sm:pt-10 pb-32 animate-in fade-in slide-in-from-bottom-10 duration-700">
        {!result ? (
          <div className="w-full max-w-6xl mx-auto py-2 md:py-4">
            <section className="overflow-hidden rounded-[32px] border border-[#e9e0d4] bg-white shadow-[0_18px_48px_rgba(71,60,51,0.14)]">
              <header className="flex flex-wrap items-center justify-between gap-4 border-b border-[#eee6d6] px-5 py-4 sm:px-7">
                <button onClick={onBack} className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-[10px] font-black uppercase tracking-[0.16em] text-[#8f8375] transition-colors hover:bg-[#f7f3ed] hover:text-[#473c33]">
                  <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M15 19l-7-7 7-7" /></svg>
                  Voltar ao Hub
                </button>
                <div className="flex items-center gap-2 rounded-full bg-[#fff6e8] px-3 py-2 text-[10px] font-black uppercase tracking-[0.18em] text-[#d88b2f]">
                  <span className="h-2 w-2 animate-pulse rounded-full bg-[#f5b84b]" />
                  {strategicMode ? 'Mergulho estratégico' : 'Exploração ilimitada'}
                </div>
              </header>

              <div className="grid lg:grid-cols-[1.02fr_0.98fr]">
                <div className="bg-[#abc270] px-6 py-8 text-[#473c33] sm:px-10 sm:py-12">
                  <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#fecc73] text-[#473c33] shadow-lg shadow-black/10">
                    <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18.5 16.5 18c-1.746 0-3.332.477-4.5 1.253" /></svg>
                  </div>
                  <p className="mt-8 text-[10px] font-black uppercase tracking-[0.3em] text-[#596b2a]">Dossiê de alto desempenho</p>
                  <h1 className="mt-3 max-w-md text-3xl font-black uppercase leading-[0.98] tracking-tight text-[#473c33] sm:text-4xl">{strategicMode ? 'Mergulho estratégico' : 'Exploração ilimitada'}</h1>
                  <p className="mt-5 max-w-md text-sm font-semibold leading-relaxed text-[#473c33]">{strategicMode ? 'Escolha uma matéria do seu edital e transforme o próximo tema em uma trilha de estudo objetiva.' : `Digite um tema e a IA cria um dossiê completo para ${studyProfile.toLowerCase()}, com resumo, exemplos e questões.`}</p>
                  <div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2">
                    <div className="rounded-2xl border border-[#f4f7ec]/70 bg-[#f4f7ec]/35 p-4">
                      <p className="text-[10px] font-black uppercase tracking-widest text-[#596b2a]">01</p>
                      <p className="mt-2 text-sm font-black text-[#473c33]">Escolha o foco</p>
                      <p className="mt-1 text-xs font-medium text-[#596b2a]">Defina o tema ou selecione no edital.</p>
                    </div>
                    <div className="rounded-2xl border border-[#f4f7ec]/70 bg-[#f4f7ec]/35 p-4">
                      <p className="text-[10px] font-black uppercase tracking-widest text-[#596b2a]">02</p>
                      <p className="mt-2 text-sm font-black text-[#473c33]">Gere seu dossiê</p>
                      <p className="mt-1 text-xs font-medium text-[#596b2a]">Receba uma trilha pronta para estudar.</p>
                    </div>
                  </div>
                </div>

                <div className="px-6 py-8 sm:px-10 sm:py-12">
                  <div className="mb-7">
                    <p className="text-[10px] font-black uppercase tracking-[0.24em] text-[#a79c8e]">Vamos começar</p>
                    <h2 className="mt-2 text-2xl font-black tracking-tight text-[#473c33]">Defina seu próximo mergulho</h2>
                    <p className="mt-2 text-sm font-medium leading-relaxed text-[#8f8375]">Ajuste o tema, a quantidade de questões e o estilo da explicação.</p>
                  </div>

                  {strategicMode && editalConfig ? (
                    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                      <label className="block">
                        <span className="mb-2 block text-[10px] font-black uppercase tracking-widest text-[#725442]">{studyProfile === 'FACULDADE' ? 'Disciplina da grade' : 'Matéria do edital'}</span>
                        <select
                          value={selectedSubject}
                          onChange={(e) => {
                            setSelectedSubject(e.target.value);
                            setSelectedTopic('');
                          }}
                          className="w-full appearance-none rounded-2xl border border-[#e3d9ca] bg-[#fdfbf7] px-4 py-4 text-sm font-semibold text-[#473c33] outline-none transition-all focus:border-[#f5b84b] focus:ring-4 focus:ring-[#f5b84b]/15"
                        >
                          <option value="">Selecionar matéria...</option>
                          {editalConfig.subjects.map((s, i) => <option key={i} value={s.name}>{s.name}</option>)}
                        </select>
                      </label>
                      <label className="block">
                        <span className="mb-2 block text-[10px] font-black uppercase tracking-widest text-[#725442]">Assunto específico</span>
                        <select value={selectedTopic} onChange={(e) => setSelectedTopic(e.target.value)} disabled={!selectedSubject} className="w-full appearance-none rounded-2xl border border-[#e3d9ca] bg-[#fdfbf7] px-4 py-4 text-sm font-semibold text-[#473c33] outline-none transition-all focus:border-[#f5b84b] focus:ring-4 focus:ring-[#f5b84b]/15 disabled:cursor-not-allowed disabled:opacity-50">
                          <option value="">Selecionar assunto...</option>
                          {editalConfig.subjects.find((s) => s.name === selectedSubject)?.topics.map((t, i) => <option key={i} value={t}>{t}</option>)}
                        </select>
                      </label>
                    </div>
                  ) : (
                    <label className="block">
                      <span className="mb-2 block text-[10px] font-black uppercase tracking-widest text-[#725442]">Tema do mergulho</span>
                      <input value={topic} onChange={(e) => setTopic(e.target.value)} placeholder="Ex.: Responsabilidade civil" className="w-full rounded-2xl border border-[#e3d9ca] bg-[#fdfbf7] px-4 py-4 text-sm font-semibold text-[#473c33] outline-none transition-all placeholder:text-[#b7ac9e] focus:border-[#f5b84b] focus:ring-4 focus:ring-[#f5b84b]/15" onKeyDown={(e) => e.key === 'Enter' && canGenerate && handleGenerate()} />
                    </label>
                  )}

                  <div className="mt-5 rounded-2xl border border-[#eee6d6] bg-[#fdfbf7] p-4">
                    <div className="flex items-center justify-between gap-3">
                      <label className="text-[10px] font-black uppercase tracking-widest text-[#725442]">Questões no caderno</label>
                      <span className="rounded-full bg-[#fff6e8] px-3 py-1 text-sm font-black text-[#d88b2f]">{numQuestions}</span>
                    </div>
                    <input type="range" min="3" max="15" value={numQuestions} onChange={(e) => setNumQuestions(Number(e.target.value))} className="mt-4 h-2 w-full cursor-pointer rounded-full accent-[#e5a83e]" />
                    <div className="mt-2 flex justify-between text-[9px] font-bold uppercase tracking-wider text-[#b7ac9e]"><span>3 questões</span><span>15 questões</span></div>
                  </div>

                  <label className="group mt-5 block">
                    <span className="mb-2 block text-[10px] font-black uppercase tracking-widest text-[#725442]">Estilo da explicação</span>
                    <textarea value={explanationStyle} onChange={(e) => setExplanationStyle(e.target.value)} placeholder="Ex.: Explique de forma simples, técnica e analítica." className="min-h-[104px] w-full resize-none rounded-2xl border border-[#e3d9ca] bg-[#fdfbf7] px-4 py-4 text-sm font-medium text-[#473c33] outline-none transition-all placeholder:text-[#b7ac9e] focus:border-[#f5b84b] focus:ring-4 focus:ring-[#f5b84b]/15" />
                    <span className="mt-2 block text-[10px] font-medium text-[#a79c8e]">Uma orientação objetiva ajuda a IA a adaptar o material.</span>
                  </label>

                  <button onClick={() => handleGenerate()} disabled={!canGenerate} className="mt-7 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#473c33] px-5 py-4 text-xs font-black uppercase tracking-[0.18em] text-white shadow-[0_10px_20px_rgba(71,60,51,0.18)] transition-all hover:bg-[#5a493f] disabled:cursor-not-allowed disabled:bg-[#d9d0c4] disabled:text-[#a79c8e] disabled:shadow-none">
                    Iniciar dossiê
                    <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M13 7l5 5m0 0l-5 5m5-5H6" /></svg>
                  </button>
                </div>
              </div>
            </section>
          </div>
        ) : (
          <div className="max-w-7xl mx-auto py-6">
            <div className="flex justify-between items-center mb-16 bg-white/5 backdrop-blur-xl p-8 rounded-[40px] border border-white/10 shadow-2xl">
              <button onClick={() => setResult(null)} className="text-gray-500 font-black uppercase text-[10px] tracking-[0.4em] flex items-center gap-3 hover:text-white transition-all group">
                <svg className="w-5 h-5 group-hover:-translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M15 19l-7-7 7-7" />
                </svg>
                NOVA PESQUISA
              </button>
              <div className="flex items-center gap-6">
                <div className="hidden md:flex flex-col items-end">
                  <span className="text-[#fecc73] text-[10px] font-black tracking-[0.4em] uppercase mb-1">Dossiê Ativo</span>
                  <span className="text-white font-black tracking-tighter uppercase">{topic}</span>
                </div>
                <button onClick={onBack} className="bg-white/10 text-white px-8 py-4 rounded-2xl font-black text-[10px] tracking-[0.4em] uppercase hover:bg-red-500 transition-all active:scale-95">
                  SAIR
                </button>
              </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start pb-32">
              <div className="lg:col-span-8 space-y-12">
                {/* RESUMO EXPANDIDO */}
                <div className="bg-white/5 rounded-[60px] p-12 md:p-20 border border-white/10 relative overflow-hidden backdrop-blur-2xl shadow-3xl">
                  <div className="absolute top-0 left-0 w-3 h-full bg-[#fec868] opacity-50"></div>
                  <div className="flex items-center gap-6 mb-16">
                    <div className="w-16 h-16 bg-[#fecc73] text-white rounded-[25px] flex items-center justify-center shadow-lg">
                      <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                      </svg>
                    </div>
                    <div>
                      <h2 className="text-[#fecc73] font-black uppercase text-[10px] tracking-[0.4em] mb-2">Resumo Executivo Expandido</h2>
                      <h3 className="text-5xl font-black tracking-tighter uppercase text-white leading-none">{topic}</h3>
                    </div>
                  </div>

                  <div className="max-w-none">
                    <div className="text-slate-100 text-2xl leading-[1.6] font-medium space-y-8">
                      <MarkdownContent content={result.executiveSummary} isDark />
                    </div>
                  </div>

                  <div className="mt-20 p-12 bg-white/[0.03] rounded-[50px] border border-white/10 shadow-inner">
                    <h4 className="text-[10px] font-black text-[#fecc73] uppercase tracking-[0.4em] mb-8 flex items-center gap-3">
                      <svg className="w-6 h-6 animate-pulse" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M13 10V3L4 14h7v7l9-11h-7z" />
                      </svg>
                      Extração de Elite: Ponto de Performance
                    </h4>
                    <div className="max-w-none">
                      <MarkdownContent content={result.deepDive} isDark />
                    </div>
                  </div>
                </div>

                {/* COMPARAÇÃO BIZURADA */}
                {result.comparison && (
                  <div className="bg-white/5 backdrop-blur-xl rounded-[60px] border border-white/10 p-12 md:p-16 relative shadow-2xl overflow-hidden">
                    <div className="absolute left-1/2 top-0 bottom-0 border-l border-white/5 -translate-x-1/2 hidden md:block"></div>
                    <div className="absolute left-1/2 top-4 -translate-x-1/2 bg-[#fec868] text-white w-14 h-14 rounded-full flex items-center justify-center font-black hidden md:flex text-2xl shadow-2xl ring-8 ring-[#473c33]">VS</div>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-20 relative">
                      <div className="space-y-8">
                        <h4 className="text-4xl font-black text-[#fdad74] uppercase tracking-tighter leading-none">{result.comparison.leftConcept}</h4>
                        <div className="max-w-none">
                          <MarkdownContent content={result.comparison.leftData?.desc || ''} isDark />
                        </div>
                        {result.comparison.leftData?.example && (
                          <div className="bg-[#fdad74]/10 p-8 rounded-[35px] text-lg text-slate-100 border border-[#fdad74]/20 shadow-lg">
                            <span className="font-black text-[#fdad74] block mb-2 uppercase tracking-widest text-xs ">EXEMPLO PRÁTICO:</span>
                            {result.comparison.leftData.example}
                          </div>
                        )}
                      </div>
                      <div className="space-y-8 md:text-right">
                        <h4 className="text-4xl font-black text-white uppercase tracking-tighter leading-none">{result.comparison.rightConcept}</h4>
                        <div className="max-w-none">
                          <MarkdownContent content={result.comparison.rightData?.desc || ''} isDark />
                        </div>
                        {result.comparison.rightData?.example && (
                          <div className="bg-white/5 p-8 rounded-[35px] text-lg text-slate-100 border border-white/10 shadow-lg">
                            <span className="font-black text-[#fecc73] block mb-2 uppercase tracking-widest text-xs ">EXEMPLO PRÁTICO:</span>
                            {result.comparison.rightData.example}
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                )}
              </div>

              <div className="lg:col-span-4 lg:sticky lg:top-24 space-y-12">
                {/* MENU DE EXPLORAÇÃO DINÂMICA */}
                <div className="bg-white/5 backdrop-blur-2xl rounded-[50px] p-10 border border-white/10 shadow-3xl">
                  <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-[0.4em] mb-10 flex items-center gap-3">
                    <span className="w-2 h-2 rounded-full bg-[#fecc73] animate-pulse"></span>
                    MAPAS DE CONEXÃO
                  </h3>
                  <div className="space-y-5">
                    {result.explorationMenu?.map((item: any, idx: number) => (
                      <button key={idx} onClick={() => handleGenerate(item.topic)} className="w-full text-left p-6 rounded-[30px] bg-white/5 hover:bg-[#fec868] transition-all group border border-transparent hover:border-white/20 active:scale-95 shadow-lg">
                        <p className="font-black text-sm uppercase tracking-tight mb-2 text-white transition-colors">{item.topic}</p>
                        <p className="text-[11px] text-slate-400 font-bold group-hover:text-[#fff0d5] leading-relaxed transition-colors line-clamp-2">{item.description}</p>
                      </button>
                    ))}
                  </div>
                </div>

                {/* SALVAR E PRATICAR */}
                <div className="bg-[#fec868] rounded-[50px] p-12 text-white shadow-[0_35px_60px_-15px_rgba(37,99,235,0.3)] relative overflow-hidden group">
                  <div className="absolute -top-32 -right-32 w-80 h-80 bg-white/10 blur-[80px] rounded-full group-hover:scale-110 transition-transform duration-1000"></div>
                  <div className="relative z-10">
                    <h3 className="text-3xl font-black mb-6 leading-none uppercase tracking-tighter">
                      Fixar <span className="text-[#ffe6b9]">conhecimento</span>
                    </h3>
                    <p className="text-[#fff0d5] text-sm mb-12 font-bold leading-relaxed uppercase tracking-widest text-[10px] opacity-80">Converta o dossier em cadernos de treino prático imediato</p>

                    <button onClick={() => setShowSaveModal(true)} disabled={saved} className={`w-full py-8 rounded-[35px] font-black text-lg flex items-center justify-center gap-4 transition-all shadow-2xl active:scale-95 ${saved ? 'bg-[#b1c77b] text-white' : 'bg-white text-[#fec868] hover:bg-[#fff6e8]'}`}>
                      {saved ? (
                        <>
                          CONDOMÍNIO SALVO
                          <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M5 13l4 4L19 7" />
                          </svg>
                        </>
                      ) : (
                        <>
                          SALVAR CADERNO
                          <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M12 4v16m8-8H4" />
                          </svg>
                        </>
                      )}
                    </button>
                  </div>
                </div>

                {/* GERAR FLASHCARDS */}
                <div className="bg-white/[0.03] backdrop-blur-xl rounded-[50px] p-12 border border-white/10 shadow-2xl relative overflow-hidden group">
                  <div className="relative z-10">
                    <h3 className="text-3xl font-black mb-6 leading-none uppercase text-white tracking-tighter">
                      Gerar <span className="text-[#fecc73]">flashcards</span>
                    </h3>
                    <p className="text-slate-500 text-xs mb-10 leading-relaxed font-black uppercase tracking-[0.3em]">IA extrai gatilhos de memória do dossiê para revisão imediata</p>

                    <button onClick={handleGenerateFlashcards} disabled={generatingCards} className={`w-full py-8 rounded-[35px] font-black text-lg flex items-center justify-center gap-4 transition-all shadow-2xl active:scale-95 ${generatingCards ? 'bg-white/5 text-gray-500 border border-white/5' : 'bg-white/5 text-white hover:bg-white/10 border-2 border-white/10'}`}>
                      {generatingCards ? 'PROCESSANDO...' : 'EXTRAIR CARDS'}
                      {!generatingCards && (
                        <svg className="w-8 h-8 text-[#fecc73]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M13 10V3L4 14h7v7l9-11h-7z" />
                        </svg>
                      )}
                    </button>
                  </div>
                </div>
              </div>
            </div>

          </div>
        )}
      </div>

      {showSaveModal && <SaveToFolderModal folders={folders} suggestedName={topic} onConfirm={handleConfirmSave} onClose={() => setShowSaveModal(false)} />}
    </div>
  );
};

export default AIView;
