
import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { generateStudyContent } from '../services/geminiService';
import LoadingFish from './LoadingFish';
import SaveToFolderModal from './SaveToFolderModal';
import { QuizFolder, QuizQuestion, StudyProfile, EditalConfig } from '../types';

interface AIViewProps {
  onBack: () => void;
  folders: QuizFolder[];
  onNewContent: (content: any) => void;
  onSaveToNotebook: (folderId: string, notebookName: string, questions: QuizQuestion[], summary?: string) => void;
  studyProfile: StudyProfile;
  prefill?: { topic: string, autoStart: boolean } | null;
  onConsumedPrefill?: () => void;
  strategicMode?: boolean;
  editalConfig?: EditalConfig;
}

const AIView: React.FC<AIViewProps> = ({ 
  onBack, 
  onNewContent, 
  onSaveToNotebook, 
  folders, 
  studyProfile, 
  prefill, 
  onConsumedPrefill,
  strategicMode,
  editalConfig
}) => {
  const [topic, setTopic] = useState(prefill?.topic || '');
  const [selectedSubject, setSelectedSubject] = useState<string>('');
  const [selectedTopic, setSelectedTopic] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [saved, setSaved] = useState(false);
  const [showSaveModal, setShowSaveModal] = useState(false);
  const [numQuestions, setNumQuestions] = useState(5);
  const [generatingCards, setGeneratingCards] = useState(false);

  React.useEffect(() => {
    if (prefill?.autoStart && prefill.topic) {
      handleGenerate(prefill.topic);
      onConsumedPrefill?.();
    }
  }, [prefill]);

  const handleGenerate = async (targetTopic?: string) => {
    const finalTopic = targetTopic || (strategicMode ? (selectedTopic ? `${selectedSubject}: ${selectedTopic}` : '') : topic);
    if (!finalTopic.trim()) return;
    
    setLoading(true);
    if (!targetTopic) setResult(null); // Reset total se for busca nova
    setSaved(false);
    
    try {
      const content = await generateStudyContent(finalTopic, "Dossiê Expandido", numQuestions, studyProfile);
      // We filter out flashcards if they were auto-generated by the service, as per user's request
      // But looking at the service, it's baked into the schema. 
      // We will keep them in the result object but not call onNewContent immediately if we want to separate logic.
      // However, onNewContent in App.tsx adds to flashcards state.
      // The user wants AI cards only when asked.
      
      const contentWithoutAutoCards = { ...content, flashcards: [] };
      setResult(content); // Keep them in state but maybe don't "activate" them yet
      if (!targetTopic) setTopic(finalTopic);
      onNewContent(contentWithoutAutoCards); 
      window.scrollTo({ top: 0, behavior: 'smooth' });
    } catch (error: any) {
      console.error(error);
      const msg = error.message || "Erro ao mergulhar. Tente novamente.";
      alert(msg);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateFlashcards = () => {
    if (!result || !result.flashcards || result.flashcards.length === 0) return;
    setGeneratingCards(true);
    
    // Simulate thinking/generating for UX
    setTimeout(() => {
      onNewContent({ ...result, quiz: [] }); // Only send flashcards
      setGeneratingCards(false);
      alert("Flashcards gerados e adicionados à sua revisão!");
    }, 1500);
  };

  const handleConfirmSave = (folderId: string, notebookName: string) => {
    if (result) {
      onSaveToNotebook(folderId, notebookName, result.quiz, result.executiveSummary);
      setSaved(true);
      setShowSaveModal(false);
    }
  };

  if (loading) {
    return <LoadingFish message="Mergulhando mais fundo..." submessage="IA está extraindo o néctar do conhecimento" />;
  }

  return (
    <div className="fixed inset-0 z-[200] bg-[#0A0F1E] text-white selection:bg-blue-500/30 overflow-y-auto font-sans">
      <div className="w-full max-w-7xl mx-auto px-6 py-12 animate-in fade-in slide-in-from-bottom-10 duration-700">
        {!result ? (
          <div className="max-w-3xl mx-auto py-20">
            <button 
              onClick={onBack} 
              className="mb-8 text-gray-500 font-black uppercase text-[10px] tracking-[0.3em] flex items-center gap-2 hover:text-white transition-all group"
            >
              <svg className="w-4 h-4 group-hover:-translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M15 19l-7-7 7-7" />
              </svg>
              VOLTAR AO HUB
            </button>
            
            <div className="text-center mb-12">
              <h1 className="text-6xl font-black mb-4 tracking-tighter italic uppercase text-white shadow-2xl">
                {strategicMode ? 'Mergulho' : 'Exploração'} <span className="text-blue-500">{strategicMode ? 'Estratégico' : 'Ilimitada'}</span>
              </h1>
              <p className="text-slate-400 font-bold uppercase tracking-[0.3em] text-[10px] opacity-60">
                {strategicMode ? 'CONECTADO AO SEU EDITAL' : `GERANDO DOSSIÊ DE ALTA PERFORMANCE PARA ${studyProfile}`}
              </p>
            </div>

            <div className="bg-white/5 backdrop-blur-2xl p-8 md:p-16 rounded-[60px] border border-white/10 shadow-2xl space-y-12">
              {strategicMode && editalConfig ? (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <div className="space-y-3">
                    <label className="text-[10px] font-black text-gray-500 uppercase tracking-[0.4em] ml-6 italic">Matéria do Edital</label>
                    <select 
                      value={selectedSubject}
                      onChange={(e) => { setSelectedSubject(e.target.value); setSelectedTopic(''); }}
                      className="w-full bg-white/5 border-2 border-white/10 rounded-[40px] px-8 py-6 text-xl focus:outline-none focus:border-blue-500 transition-all font-black text-white appearance-none cursor-pointer"
                    >
                      <option value="" className="bg-[#0A0F1E]">Selecionar Matéria...</option>
                      {editalConfig.subjects.map((s, i) => (
                        <option key={i} value={s.name} className="bg-[#0A0F1E]">{s.name}</option>
                      ))}
                    </select>
                  </div>
                  <div className="space-y-3">
                    <label className="text-[10px] font-black text-gray-500 uppercase tracking-[0.4em] ml-6 italic">Assunto Específico</label>
                    <select 
                      value={selectedTopic}
                      onChange={(e) => setSelectedTopic(e.target.value)}
                      disabled={!selectedSubject}
                      className="w-full bg-white/5 border-2 border-white/10 rounded-[40px] px-8 py-6 text-xl focus:outline-none focus:border-blue-500 transition-all font-black text-white appearance-none cursor-pointer disabled:opacity-20"
                    >
                      <option value="" className="bg-[#0A0F1E]">Selecionar Assunto...</option>
                      {editalConfig.subjects.find(s => s.name === selectedSubject)?.topics.map((t, i) => (
                        <option key={i} value={t} className="bg-[#0A0F1E]">{t}</option>
                      ))}
                    </select>
                  </div>
                </div>
              ) : (
                <div className="space-y-4">
                  <label className="text-[10px] font-black text-gray-500 uppercase tracking-[0.4em] ml-8 italic">O que você quer mergulhar hoje?</label>
                  <input 
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    placeholder="DIGITE O TEMA DO SEU MERGULHO..."
                    className="w-full bg-white/5 border-2 border-white/10 rounded-[40px] px-10 py-10 text-3xl focus:outline-none focus:border-blue-500 transition-all placeholder:text-white/5 font-black text-white text-center italic"
                    onKeyPress={(e) => e.key === 'Enter' && handleGenerate()}
                  />
                </div>
              )}
              
              <div className="flex flex-col md:flex-row gap-8 items-center justify-between pt-4">
                <div className="flex-1 w-full bg-white/5 p-8 rounded-[40px] border border-white/5">
                  <div className="flex justify-between mb-4">
                     <label className="text-[10px] font-black text-gray-400 uppercase tracking-[0.3em]">Questões no Caderno</label>
                     <span className="text-blue-500 font-black text-xl">{numQuestions}</span>
                  </div>
                  <input 
                    type="range" min="3" max="15" 
                    value={numQuestions}
                    onChange={(e) => setNumQuestions(Number(e.target.value))}
                    className="w-full h-2 bg-white/10 rounded-full accent-blue-500 cursor-pointer"
                  />
                </div>
                <button 
                  onClick={() => handleGenerate()}
                  className="w-full md:w-auto bg-blue-600 text-white px-16 py-8 rounded-[40px] font-black text-2xl hover:bg-blue-500 transition-all active:scale-95 flex items-center justify-center gap-4 shadow-2xl shadow-blue-900/40 uppercase tracking-tighter italic"
                >
                  INICIAR DOSSIÊ
                  <svg className="w-8 h-8 text-white/50" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M13 7l5 5m0 0l-5 5m5-5H6" /></svg>
                </button>
              </div>
            </div>
          </div>
        ) : (
          <div className="max-w-7xl mx-auto py-6">
            <div className="flex justify-between items-center mb-16 bg-white/5 backdrop-blur-xl p-8 rounded-[40px] border border-white/10 shadow-2xl">
              <button 
                onClick={() => setResult(null)} 
                className="text-gray-500 font-black uppercase text-[10px] tracking-[0.4em] flex items-center gap-3 hover:text-white transition-all group"
              >
                <svg className="w-5 h-5 group-hover:-translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M15 19l-7-7 7-7" />
                </svg>
                NOVA PESQUISA
              </button>
              <div className="flex items-center gap-6">
                 <div className="hidden md:flex flex-col items-end">
                   <span className="text-blue-500 text-[10px] font-black tracking-[0.4em] uppercase mb-1">Dossiê Ativo</span>
                   <span className="text-white font-black italic tracking-tighter uppercase">{topic}</span>
                 </div>
                 <button 
                   onClick={onBack} 
                   className="bg-white/10 text-white px-8 py-4 rounded-2xl font-black text-[10px] tracking-[0.4em] uppercase hover:bg-red-500 transition-all active:scale-95"
                 >
                   SAIR
                 </button>
              </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start pb-32">
              <div className="lg:col-span-8 space-y-12">
                
                {/* RESUMO EXPANDIDO */}
                <div className="bg-white/5 rounded-[60px] p-12 md:p-20 border border-white/10 relative overflow-hidden backdrop-blur-2xl shadow-3xl">
                  <div className="absolute top-0 left-0 w-3 h-full bg-blue-600 opacity-50"></div>
                  <div className="flex items-center gap-6 mb-16">
                    <div className="w-16 h-16 bg-blue-500 text-white rounded-[25px] flex items-center justify-center shadow-lg shadow-blue-900/40">
                      <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" /></svg>
                    </div>
                    <div>
                      <h2 className="text-blue-500 font-black uppercase text-[10px] tracking-[0.4em] mb-2">Resumo Executivo Expandido</h2>
                      <h3 className="text-5xl font-black italic tracking-tighter uppercase text-white leading-none">{topic}</h3>
                    </div>
                  </div>
                  
                  <div className="prose prose-invert prose-2xl max-w-none markdown-body">
                    <div className="text-slate-100 text-2xl leading-[1.6] font-medium space-y-8">
                      <ReactMarkdown>{result.executiveSummary}</ReactMarkdown>
                    </div>
                  </div>

                  <div className="mt-20 p-12 bg-white/[0.03] rounded-[50px] border border-white/10 shadow-inner">
                    <h4 className="text-[10px] font-black text-blue-500 uppercase tracking-[0.4em] mb-8 flex items-center gap-3">
                      <svg className="w-6 h-6 animate-pulse" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
                      Extração de Elite: Ponto de Performance
                    </h4>
                    <div className="text-slate-300 text-xl leading-relaxed font-medium markdown-body prose prose-invert prose-blue prose-xl max-w-none">
                      <ReactMarkdown>{result.deepDive}</ReactMarkdown>
                    </div>
                  </div>
                </div>

                {/* COMPARAÇÃO BIZURADA */}
                {result.comparison && (
                  <div className="bg-white/5 backdrop-blur-xl rounded-[60px] border border-white/10 p-12 md:p-16 relative shadow-2xl overflow-hidden">
                    <div className="absolute left-1/2 top-0 bottom-0 border-l border-white/5 -translate-x-1/2 hidden md:block"></div>
                    <div className="absolute left-1/2 top-4 -translate-x-1/2 bg-blue-600 text-white w-14 h-14 rounded-full flex items-center justify-center font-black italic hidden md:flex text-2xl shadow-2xl ring-8 ring-[#0A0F1E]">VS</div>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-20 relative">
                      <div className="space-y-8">
                        <h4 className="text-4xl font-black text-orange-500 uppercase italic tracking-tighter leading-none">{result.comparison.leftConcept}</h4>
                        <div className="text-xl text-slate-300 font-medium markdown-body prose prose-invert prose-xl max-w-none">
                          <ReactMarkdown>{result.comparison.leftData?.desc || ''}</ReactMarkdown>
                        </div>
                        {result.comparison.leftData?.example && (
                          <div className="bg-orange-500/10 p-8 rounded-[35px] text-lg italic text-slate-100 border border-orange-500/20 shadow-lg">
                            <span className="font-black text-orange-500 block mb-2 uppercase tracking-widest text-xs italic">EXEMPLO PRÁTICO:</span>
                            {result.comparison.leftData.example}
                          </div>
                        )}
                      </div>
                      <div className="space-y-8 md:text-right">
                        <h4 className="text-4xl font-black text-white uppercase italic tracking-tighter leading-none">{result.comparison.rightConcept}</h4>
                        <div className="text-xl text-slate-300 font-medium markdown-body prose prose-invert prose-xl max-w-none">
                          <ReactMarkdown>{result.comparison.rightData?.desc || ''}</ReactMarkdown>
                        </div>
                        {result.comparison.rightData?.example && (
                          <div className="bg-white/5 p-8 rounded-[35px] text-lg italic text-slate-100 border border-white/10 shadow-lg">
                            <span className="font-black text-blue-500 block mb-2 uppercase tracking-widest text-xs italic">EXEMPLO PRÁTICO:</span>
                            {result.comparison.rightData.example}
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                )}
              </div>

              <div className="lg:col-span-4 lg:sticky lg:top-24 space-y-12">
                
                {/* MENU DE EXPLORAÇÃO DINÂMICA */}
                <div className="bg-white/5 backdrop-blur-2xl rounded-[50px] p-10 border border-white/10 shadow-3xl">
                  <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-[0.4em] mb-10 flex items-center gap-3">
                     <span className="w-2 h-2 rounded-full bg-blue-500 animate-pulse"></span>
                     MAPAS DE CONEXÃO
                  </h3>
                  <div className="space-y-5">
                    {result.explorationMenu?.map((item: any, idx: number) => (
                      <button 
                        key={idx}
                        onClick={() => handleGenerate(item.topic)}
                        className="w-full text-left p-6 rounded-[30px] bg-white/5 hover:bg-blue-600 transition-all group border border-transparent hover:border-white/20 active:scale-95 shadow-lg"
                      >
                        <p className="font-black text-sm uppercase tracking-tight mb-2 text-white transition-colors">{item.topic}</p>
                        <p className="text-[11px] text-slate-400 font-bold group-hover:text-blue-100 leading-relaxed transition-colors line-clamp-2">
                          {item.description}
                        </p>
                      </button>
                    ))}
                  </div>
                </div>

                {/* SALVAR E PRATICAR */}
                <div className="bg-blue-600 rounded-[50px] p-12 text-white shadow-[0_35px_60px_-15px_rgba(37,99,235,0.3)] relative overflow-hidden group">
                  <div className="absolute -top-32 -right-32 w-80 h-80 bg-white/10 blur-[80px] rounded-full group-hover:scale-110 transition-transform duration-1000"></div>
                  <div className="relative z-10">
                    <h3 className="text-3xl font-black mb-6 leading-none italic uppercase tracking-tighter">Fixar <span className="text-blue-200">conhecimento</span></h3>
                    <p className="text-blue-100 text-sm mb-12 font-bold leading-relaxed uppercase tracking-widest text-[10px] opacity-80">Converta o dossier em cadernos de treino prático imediato</p>
                    
                    <button 
                      onClick={() => setShowSaveModal(true)}
                      disabled={saved}
                      className={`w-full py-8 rounded-[35px] font-black text-lg flex items-center justify-center gap-4 transition-all shadow-2xl active:scale-95 ${saved ? 'bg-green-500 text-white' : 'bg-white text-blue-600 hover:bg-blue-50'}`}
                    >
                      {saved ? (
                        <>
                          CONDOMÍNIO SALVO
                          <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M5 13l4 4L19 7" /></svg>
                        </>
                      ) : (
                        <>
                          SALVAR CADERNO
                          <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M12 4v16m8-8H4" /></svg>
                        </>
                      )}
                    </button>
                  </div>
                </div>

                {/* GERAR FLASHCARDS */}
                <div className="bg-white/[0.03] backdrop-blur-xl rounded-[50px] p-12 border border-white/10 shadow-2xl relative overflow-hidden group">
                  <div className="relative z-10">
                    <h3 className="text-3xl font-black mb-6 leading-none italic uppercase text-white tracking-tighter">Gerar <span className="text-blue-500">flashcards</span></h3>
                    <p className="text-slate-500 text-xs mb-10 leading-relaxed font-black uppercase tracking-[0.3em]">IA extrai gatilhos de memória do dossiê para revisão imediata</p>
                    
                    <button 
                      onClick={handleGenerateFlashcards}
                      disabled={generatingCards}
                      className={`w-full py-8 rounded-[35px] font-black text-lg flex items-center justify-center gap-4 transition-all shadow-2xl active:scale-95 ${generatingCards ? 'bg-white/5 text-gray-500 border border-white/5' : 'bg-white/5 text-white hover:bg-white/10 border-2 border-white/10'}`}
                    >
                      {generatingCards ? 'PROCESSANDO...' : 'EXTRAIR CARDS'}
                      {!generatingCards && <svg className="w-8 h-8 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>}
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {showSaveModal && (
        <SaveToFolderModal 
          folders={folders}
          suggestedName={topic}
          onConfirm={handleConfirmSave}
          onClose={() => setShowSaveModal(false)}
        />
      )}
    </div>
  );
};

export default AIView;
